In [7]:
import warnings
warnings.filterwarnings('ignore',category=FutureWarning)
warnings.filterwarnings('ignore',category=DeprecationWarning)
import sys
sys.path.append('..')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from cuml.ensemble import RandomForestRegressor as cuRF
from sklearn.ensemble import RandomForestRegressor as RF
import cudf
import cupy
import xgboost as xgb
from scripts.function_utils import past_timesteps, test_leave_house_out, total_averaged_metrics

#### Output file

In [2]:
sourceFile = open("../../gpu_logs/test_porto.txt", 'w')

### Load the data

In [ ]:
df = pd.read_csv("../../data/porto.csv", decimal=",", index_col=[0])
## Leaving the first house (public building out) due to its different profile
df['Energy'] = df['Energy'].astype(np.float32)
df = df.iloc[:, [0, 2, 1]].reset_index(drop=True)
number_of_houses = df.Location.nunique()
df['Time'] = pd.to_datetime(df['Time'])
df.reset_index(drop=True, inplace=True)
df

## Save Dataframe with past timesteps

In [ ]:
number_of_timesteps = 96

In [ ]:
# df_new = past_timesteps(df, number_of_timesteps)
# df_new

In [ ]:
# df_new['DayOfWeek'] = df_new['Time'].dt.dayofweek
# df_new['Weekend'] = df_new['Time'].dt.dayofweek.isin([5, 6]).astype(int)
# df_new['Hour'] = df_new['Time'].dt.hour
# df_new

In [ ]:
# df_selected = df_new[["Time","Location","lag_1","lag_2","lag_3","lag_4","lag_96","lag_192","lag_288","lag_384","lag_480","lag_576","lag_672","DayOfWeek","Hour","Energy"]]
# df_selected

In [3]:
#df_selected.to_csv("../../data/porto_full_selected.csv", index=False)

## Predict  5 folds with 10 random houses for test

In [2]:
df_test = pd.read_csv("../../data/porto_full_selected.csv", nrows=100)

float_cols = [c for c in df_test if df_test[c].dtype == "float64"]
float32_cols = {c: np.float32 for c in float_cols}

df = pd.read_csv("../../data/porto_full_selected.csv", engine='c', dtype=float32_cols)
df

Time  Location     lag_1     lag_2     lag_3  \
0        2019-01-08 00:00:00         0  3.952000  3.803000  4.095000   
1        2019-01-08 00:15:00         0  4.940000  3.952000  3.803000   
2        2019-01-08 00:30:00         0  4.149000  4.940000  3.952000   
3        2019-01-08 00:45:00         0  4.401000  4.149000  4.940000   
4        2019-01-08 01:00:00         0  4.431000  4.401000  4.149000   
...                      ...       ...       ...       ...       ...   
1757659  2020-01-01 22:45:00        50  1.099100  0.453906  0.481770   
1757660  2020-01-01 23:00:00        50  0.753222  1.099100  0.453906   
1757661  2020-01-01 23:15:00        50  0.716855  0.753222  1.099100   
1757662  2020-01-01 23:30:00        50  0.735802  0.716855  0.753222   
1757663  2020-01-01 23:45:00        50  0.485237  0.735802  0.716855   

            lag_4    lag_96   lag_192   lag_288   lag_384   lag_480   lag_576  \
0        3.926000  2.615000  3.321000  3.066000  2.351000  2.851000  3.054000   
1        4.095000  2.634000  2.873000  3.152000  2.843000  3.102000  2.677000   
2        3.803000  3.052000  3.407000  2.633000  2.949000  2.546000  3.522000   
3        3.952000  2.893000  2.673000  2.590000  2.605000  3.016000  2.729000   
4        4.940000  2.349000  2.390000  2.330000  3.023000  3.031000  2.368000   
...           ...       ...       ...       ...       ...       ...       ...   
1757659  0.483173  0.641933  0.778195  0.753222  0.641933  0.778195  0.753222   
1757660  0.481770  0.752850  0.931837  0.716855  0.752850  0.931837  0.716855   
1757661  0.453906  0.935428  0.937079  0.735802  0.935428  0.937079  0.735802   
1757662  1.099100  0.715781  0.803087  0.485237  0.715781  0.803087  0.485237   
1757663  0.753222  1.077717  0.600777  0.394216  1.077717  0.600777  0.394216   

          lag_672  DayOfWeek  Hour    Energy  
0        2.964000          1     0  4.940000  
1        2.584000          1     0  4.149000  
2        3.071000          1     0  4.401000  
3        2.694000          1     0  4.431000  
4        2.569000          1     1  3.988000  
...           ...        ...   ...       ...  
1757659  1.723943          2    22  0.753222  
1757660  1.482914          2    23  0.716855  
1757661  1.772033          2    23  0.735802  
1757662  2.535657          2    23  0.485237  
1757663  2.055415          2    23  0.394216  

[1757664 rows x 16 columns]

In [5]:
cu_df = cudf.read_csv("../../data/porto_full_selected.csv")
cu_df

Time  Location     lag_1     lag_2     lag_3  \
0        2019-01-08 00:00:00         0  3.952000  3.803000  4.095000   
1        2019-01-08 00:15:00         0  4.940000  3.952000  3.803000   
2        2019-01-08 00:30:00         0  4.149000  4.940000  3.952000   
3        2019-01-08 00:45:00         0  4.401000  4.149000  4.940000   
4        2019-01-08 01:00:00         0  4.431000  4.401000  4.149000   
...                      ...       ...       ...       ...       ...   
1757659  2020-01-01 22:45:00        50  1.099100  0.453906  0.481770   
1757660  2020-01-01 23:00:00        50  0.753222  1.099100  0.453906   
1757661  2020-01-01 23:15:00        50  0.716855  0.753222  1.099100   
1757662  2020-01-01 23:30:00        50  0.735802  0.716855  0.753222   
1757663  2020-01-01 23:45:00        50  0.485237  0.735802  0.716855   

            lag_4    lag_96   lag_192   lag_288   lag_384   lag_480   lag_576  \
0        3.926000  2.615000  3.321000  3.066000  2.351000  2.851000  3.054000   
1        4.095000  2.634000  2.873000  3.152000  2.843000  3.102000  2.677000   
2        3.803000  3.052000  3.407000  2.633000  2.949000  2.546000  3.522000   
3        3.952000  2.893000  2.673000  2.590000  2.605000  3.016000  2.729000   
4        4.940000  2.349000  2.390000  2.330000  3.023000  3.031000  2.368000   
...           ...       ...       ...       ...       ...       ...       ...   
1757659  0.483173  0.641933  0.778195  0.753222  0.641933  0.778195  0.753222   
1757660  0.481770  0.752850  0.931837  0.716855  0.752850  0.931837  0.716855   
1757661  0.453906  0.935428  0.937079  0.735802  0.935428  0.937079  0.735802   
1757662  1.099100  0.715781  0.803087  0.485237  0.715781  0.803087  0.485237   
1757663  0.753222  1.077717  0.600777  0.394216  1.077717  0.600777  0.394216   

          lag_672  DayOfWeek  Hour    Energy  
0        2.964000          1     0  4.940000  
1        2.584000          1     0  4.149000  
2        3.071000          1     0  4.401000  
3        2.694000          1     0  4.431000  
4        2.569000          1     1  3.988000  
...           ...        ...   ...       ...  
1757659  1.723943          2    22  0.753222  
1757660  1.482914          2    23  0.716855  
1757661  1.772034          2    23  0.735802  
1757662  2.535657          2    23  0.485237  
1757663  2.055415          2    23  0.394216  

[1757664 rows x 16 columns]

In [6]:
#df = df[["Time", "Location", "energy_lag_1", "energy_lag_3", "energy_lag_95", "energy_lag_671", "Energy"]]
#df

In [7]:
num_houses_test = 10
locations = []
for i in range(10):
    np.random.seed(i*4)
    l = np.random.choice(df['Location'].unique(), size=num_houses_test, replace=False)
    locations.append(l)
locations

[array([29, 11, 10, 22,  2, 28, 45, 32, 26,  4]),
 array([27,  6, 25,  7, 49, 18, 24,  4, 11, 14]),
 array([49, 35,  1, 50,  0, 22, 25, 31, 45, 32]),
 array([28, 47,  7, 42, 37, 29, 21, 49, 19,  8]),
 array([ 3, 35, 25, 37, 20, 23, 36, 21, 43, 40]),
 array([47,  4, 38, 18, 46, 43, 29, 12, 17,  8]),
 array([20,  8, 37,  5, 19, 33,  2, 30, 41, 21]),
 array([48, 11, 21, 35, 18, 29, 10, 47, 20, 37]),
 array([50, 16, 38, 36, 45,  8, 32, 12, 26,  2]),
 array([29, 11, 18, 32, 12, 35, 38, 16,  2,  8])]

In [8]:
## Number of NaNs
df.isna().sum().sum()

0

In [9]:
#kf = RepeatedKFold(n_splits=5, n_repeats=2, random_state=42) 
#locations = []
#for _, test_index in kf.split(df['Location'].unique()):
#    locations.append(test_index)
#locations

In [10]:
df.Location.value_counts()

0     34464
38    34464
28    34464
29    34464
30    34464
31    34464
32    34464
33    34464
34    34464
35    34464
36    34464
37    34464
39    34464
26    34464
40    34464
41    34464
42    34464
43    34464
44    34464
45    34464
46    34464
47    34464
48    34464
49    34464
27    34464
25    34464
1     34464
12    34464
2     34464
3     34464
4     34464
5     34464
6     34464
7     34464
8     34464
9     34464
10    34464
11    34464
13    34464
24    34464
14    34464
15    34464
16    34464
17    34464
18    34464
19    34464
20    34464
21    34464
22    34464
23    34464
50    34464
Name: Location, dtype: int64

### Linear Regression

In [11]:
metrics_list_lr = []
print("\n----------------------------", file=sourceFile)
print("\nLinear Regression\n", file=sourceFile)
print("----------------------------\n", file=sourceFile)
for i in range(1):
    print("\nIteration", i, file=sourceFile)
    print("\nIteration", i)
    mse, wape, r2, model_lr = test_leave_house_out(df, LinearRegression(), locations[i], sourceFile, split_timeseries=True)
    metrics_list_lr.append((mse, wape, r2))


Iteration 0
split timeseries
Train set:  (1433692, 16)
Test set:  (358436, 16)
MSE: 0.3085
RMSE: 0.5554
WAPE: 28.35
R2: 0.8751


### XGBoost

In [12]:
metrics_list_xgb = []
print("\n----------------------------", file=sourceFile)
print("\nXGBoost\n", file=sourceFile)
print("----------------------------\n", file=sourceFile)
for i in range(1):
    print("\nIteration", i, file=sourceFile)
    print("\nIteration", i)
    mse, wape, r2, model_xgb = test_leave_house_out(df, xgb.XGBRegressor(tree_method='gpu_hist', seed=0, colsample_bytree=0.7, learning_rate=0.1, max_depth=12, n_estimators=1000), locations[i], sourceFile, split_timeseries=True)
    metrics_list_xgb.append((mse, wape, r2))


Iteration 0
split timeseries
Train set:  (1433692, 16)
Test set:  (358436, 16)
MSE: 1.1745
RMSE: 1.0837
WAPE: 30.85
R2: 0.5245


### Random Forest

In [ ]:
metrics_list_rf = []
print("\n----------------------------", file=sourceFile)
print("\nRandom Forest\n", file=sourceFile)
print("----------------------------\n", file=sourceFile)
for i in range(10):
    print("\nIteration", i, file=sourceFile)
    print("\nIteration", i)
    mse, wape, r2, model_rf = test_leave_house_out(cu_df, cuRF(max_depth=16, n_estimators=500, max_batch_size=60), locations[i], sourceFile, split_timeseries=True, gpu=True)
    metrics_list_rf.append((mse, wape, r2))

## Averaged Metrics

In [ ]:
print("\n\n\n", file=sourceFile)

In [ ]:
print("\nLinear Regression", file=sourceFile)
total_averaged_metrics(metrics_list_lr, sourceFile)

In [ ]:
print("\nXGBoost", file=sourceFile)
total_averaged_metrics(metrics_list_xgb, sourceFile)

In [ ]:
print("\nRandom Forest", file=sourceFile)
total_averaged_metrics(metrics_list_rf, sourceFile)

In [ ]:
sourceFile.close()

### Feature Importance

In [ ]:
print('XGBoost\n')
for i,v in enumerate(model_xgb.feature_importances_):
    print('Feature: %0d, Score: %.5f' % (i,v))

In [ ]:
model_xgb.feature_importances_

In [ ]:
plt.figure(figsize=(22,6))
plt.bar(df.columns[2:-1],model_xgb.feature_importances_)
plt.title('Feature Importance')
plt.xlabel('Feature')
plt.ylabel('Importance')
plt.savefig("images/porto_xgb_final7days_feature_importance.png")
plt.show()

In [ ]:
plt.figure(figsize=(12,6))
plt.bar(df.columns[2:-1],model_lr.coef_)
plt.title('Feature Importance')
plt.xlabel('Feature')
plt.ylabel('Importance')
plt.show()

In [ ]:
columns = df.drop(["Energy", "Location", "Time"], axis=1).columns
feature_importance = pd.Series(model_xgb.feature_importances_, index=columns)
feature_importance

In [ ]:
features = feature_importance.nlargest(40).index
features

In [ ]:
df_40 = df[['Time', 'Location'] + [*features] + ['Energy']]
df_40

In [ ]:
df_40.to_csv("data/porto_best40features.csv", index=False)

## Hyperparameter Tuning

In [2]:
df_test = pd.read_csv("../../data/porto_full_selected.csv", nrows=100)

float_cols = [c for c in df_test if df_test[c].dtype == "float64"]
float32_cols = {c: np.float32 for c in float_cols}

df_tuning = pd.read_csv("../../data/porto_full_selected.csv", engine='c', dtype=float32_cols)
df_tuning.drop(['Time', 'Location'],axis=1, inplace=True)
df_tuning

lag_1     lag_2     lag_3     lag_4    lag_96   lag_192   lag_288  \
0        3.952000  3.803000  4.095000  3.926000  2.615000  3.321000  3.066000   
1        4.940000  3.952000  3.803000  4.095000  2.634000  2.873000  3.152000   
2        4.149000  4.940000  3.952000  3.803000  3.052000  3.407000  2.633000   
3        4.401000  4.149000  4.940000  3.952000  2.893000  2.673000  2.590000   
4        4.431000  4.401000  4.149000  4.940000  2.349000  2.390000  2.330000   
...           ...       ...       ...       ...       ...       ...       ...   
1757659  1.099100  0.453906  0.481770  0.483173  0.641933  0.778195  0.753222   
1757660  0.753222  1.099100  0.453906  0.481770  0.752850  0.931837  0.716855   
1757661  0.716855  0.753222  1.099100  0.453906  0.935428  0.937079  0.735802   
1757662  0.735802  0.716855  0.753222  1.099100  0.715781  0.803087  0.485237   
1757663  0.485237  0.735802  0.716855  0.753222  1.077717  0.600777  0.394216   

          lag_384   lag_480   lag_576   lag_672  DayOfWeek  Hour    Energy  
0        2.351000  2.851000  3.054000  2.964000          1     0  4.940000  
1        2.843000  3.102000  2.677000  2.584000          1     0  4.149000  
2        2.949000  2.546000  3.522000  3.071000          1     0  4.401000  
3        2.605000  3.016000  2.729000  2.694000          1     0  4.431000  
4        3.023000  3.031000  2.368000  2.569000          1     1  3.988000  
...           ...       ...       ...       ...        ...   ...       ...  
1757659  0.641933  0.778195  0.753222  1.723943          2    22  0.753222  
1757660  0.752850  0.931837  0.716855  1.482914          2    23  0.716855  
1757661  0.935428  0.937079  0.735802  1.772033          2    23  0.735802  
1757662  0.715781  0.803087  0.485237  2.535657          2    23  0.485237  
1757663  1.077717  0.600777  0.394216  2.055415          2    23  0.394216  

[1757664 rows x 14 columns]

In [14]:
params_rf = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300]
}

In [4]:
params_xgb = { 
    'max_depth': [3,6,10],
    'learning_rate': [0.01, 0.05, 0.1],
    'n_estimators': [100, 500, 1000],
    'colsample_bytree': [0.3, 0.7]
}

In [5]:
train_features = df_tuning.drop('Energy', axis=1)
train_labels = df_tuning['Energy']
test_features = 0
test_labels = 0

### XGBoost Best Parameters

In [ ]:
xgb_model = xgb.XGBRegressor(tree_method="gpu_hist", seed=42)
grid_search = GridSearchCV(estimator = xgb_model, param_grid = params_xgb, cv = 5, n_jobs = 4, verbose = 2, scoring="r2")

In [ ]:
grid_search.fit(train_features, train_labels)

In [ ]:
grid_search.best_params_
#{'colsample_bytree': 0.7,
#'learning_rate': 0.1,
#'max_depth': 10,
#'n_estimators': 1000}

In [ ]:
grid_search.best_score_

### Random Forest Best Parameters

In [15]:
rf = RF()
grid_search_rf = GridSearchCV(estimator = rf, param_grid = params_rf, cv = 5, n_jobs = 16, verbose = 2, scoring="r2")

In [ ]:
grid_search_rf.fit(train_features, train_labels)

In [ ]:
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy

In [ ]:
print(grid_search.best_params_)
best_grid = grid_search.best_estimator_
#grid_accuracy = evaluate(best_grid, test_features, test_labels)

In [ ]:
base_model = xgb.XGBRegressor(n_estimators = 10, random_state = 42, tree_method="gpu_hist")
base_model.fit(train_features, train_labels)
base_accuracy = evaluate(base_model, test_features, test_labels)

best_random = grid_search.best_estimator_
random_accuracy = evaluate(best_random, test_features, test_labels)

print('Improvement of {:0.2f}%.'.format( 100 * (random_accuracy - base_accuracy) / base_accuracy))

In [ ]:
#print('Improvement of {:0.2f}%.'.format( 100 * (grid_accuracy - base_accuracy) / base_accuracy))